# Generated by Django 3.1.2 on 2020-10-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profileOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('about_me', models.TextField(max_length=100)),
                ('friend', models.ManyToManyField(blank=True, related_name='_profileowner_friend_+', to='manytomany.profileOwner')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profilePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.CharField(default='', max_length=100)),
                ('profileowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.profileowner')),
            ],
        ),
        migrations.CreateModel(
            name='friendComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.profileowner')),
                ('profileposts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.profileposts')),
            ],
        ),
    ]
