# Generated by Django 3.1.2 on 2020-10-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_remove_friendcomments_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcomments',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manytomany.profileowner'),
            preserve_default=False,
        ),
    ]
